language: node_js
node_js:
  - "7"

before_deploy:
  - hexo generate 
deploy:
  provider: pages 
  skip_cleanup: true 
  on:
    branch: master
env:
  global:
    secure: SHzD7/ZA4h5l559MRLCWu+cO0G1PblpUCwPB/cgxmzzCI2lOTgWZhOakbfLPnDaeztYoVBXjiLg7vTKtKghcxXM1bHV0VgHDg/T+9emJnOzNa6gYgG1YhcMLRbIUYiUD96/XtLx/lbD5WaCEhS07NOT9Op8GWPern1vmCM7De9ywWiS47xjL0304QNqilYHxlJGBoKamMNk3N6aesGiEFZ0TUYAjqrsM08n5vYSydtune9nbY8blOYSaoEQfRVyZ9QWMuB+xvYqBdLdcA94b8kF97cG7HUGGwMi/QlhBBnewTXH6pku4HGkAgTXc6phg220SFjI1DxhvHcJiJwRHplfScI6BP3Wb2dCpr1qmeXMUUyNCyUusZkq3wIvHGiXQURDPFsnZt7gB/MRQuwOC8hHYHFUMc1a0vh/zom8kXEuNVBDPUpTJJMW+yTeTPnN7DQjG0omlEOszC52gjZ64beNn5Oz8fqYa6ax0jppEy0X+5HwcvcZnwN+xnw+IFXSVQ9bBBCblgFM5rllXiSwgedG0x/TL8LLugBWoQsuUbdqvp0T7J+CjtFCLfRDBH6Xyt3KEJtccaQ+oJ0K8fRCuDyzfcylv1delXVSQlPdyItAMZJbHX3WvyRgEbWf+dQA0aLHbOE+D6zxFe7nLqFIJFEbTQh2F0yDVJBW8w6CPzd4=
