language: node_js
node_js:
  - "8"

before_deploy:
  - hexo generate 
deploy:
  provider: pages 
  skip_cleanup: true 
  github-token: $GITHUB_TOKEN
  on:
    branch: source
  repo: thesunnysky/thesunnysky.github.io
  local_dir: public
  target_branch: master
